#!/bin/bash

# allow all docker hosts to our X server
xhost +local:docker

# start our container and a terminal
docker run \
       -it \
       --rm \
      -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
      -v ${HOME}:/developer/shared \
      -e DISPLAY=unix${DISPLAY} \
      -p 8989:8989 \
      --device /dev/snd \
      --privileged \
      --name anyconnect-remmina \
      cmiles74/docker-openconnect-freerdp

